<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Crimson+Text:400,400italic,700,700italic');
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('css/style.css'));
$this->headScript()->prependFile($this->assetUrl('js/centerrow.js'));
$this->headScript()->prependFile($this->assetUrl('js/jquery-accessibleMegaMenu.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->jsTranslate();
$banner = $this->themeSettingAssetUrl('banner');
$bannerHeight = $this->themeSetting('banner_height');
$bannerHeightMobile = $this->themeSetting('banner_height_mobile');
$bannerPosition = ($this->themeSetting('banner_position')) ? str_replace('_','-', $this->themeSetting('banner_position')) : 'center';
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        <style>
            .banner {
                height: <?php echo ($bannerHeight !== '') ? $bannerHeight: 'auto'  ?>;
                align-items: <?php echo $bannerPosition; ?>;
            }
        <?php if ($bannerHeightMobile !== ''): ?>
            @media screen and (max-width:640px) {
                .banner {
                    height: <?php echo $bannerHeightMobile; ?>;
                }
            }
        <?php endif; ?>
        </style>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
        <?php echo $userBar; ?>

        <div id="main-menu">
          <style>
            header nav .navigation {
              background-color: #951936;
              position: relative;
              list-style-type: none;
              padding: 0;
              display: flex;
              justify-content: space-between;
              align-items: stretch;
              border-top: 0 solid #dedede;
              border-bottom: 0 solid #dedede;
              padding: 0 24px;
              margin: 0;
            }
            header nav .navigation a {
              color: white;
              font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            }
            .crnc-banner {
              background-image: url("http://northerncity.library.temple.edu/themes/civil-rights/css/body.png");
              background-repeat: repeat-x;
              position: relative;
              top: -48px;
              height: 120px;
            }
            .crnc-banner h1 {
            }
            .crnc-banner h1 a {
              color: white;
              text-align: left;
              text-shadow: 2px 2px 2px #951936;
              padding-left: 3rem;
              padding-top: 2px;
              font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            }
            .crnc-banner h1 img {
              float: right;
              padding-right: 28px;
            }
          </style>
        </div>

        <header>
          <?php echo $site->publicNav()->menu()->setPartial('common/accessible-mega-menu.phtml')->renderPartial(); ?>
          <div class="crnc-banner">
            <h1>
              <img src="http://northerncity.library.temple.edu/themes/civil-rights/css/temple-logo.png" />
              <a href="<?php echo $site->url(); ?>" class="site-title">
              <?php if ($this->themeSetting('logo')): ?>
                  <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
              <?php else: ?>
                  <?php echo $escape($siteTitle); ?>
              <?php endif; ?>
              </a>
            </h1>
          </div>
        </header>

        <div id="wrap">
            <div id="content" role="main">
                <?php echo $this->content; ?>
            </div>

            <footer>
                <?php if ($footerContent = $this->themeSetting('footer')): ?>
                <?php echo $footerContent; ?>
                <?php else: ?>
                    <?php echo $this->translate('Powered by Omeka S'); ?>
                <?php endif; ?>
            </footer>
        </div>
        <script type="text/javascript">
        jQuery(document).ready(function () {
            CenterRow.mobileMenu();
            CenterRow.megaMenu();
        });
        </script>
    </body>
</html>
